version: 2
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
  commands:
    - pip install uv
    - uv venv -p 3.14
    - uv pip install tox tox-uv
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - .venv/bin/tox --verbose -e docs
