[build-system]
requires = [
    "hatchling >= 1.26",
]
build-backend = "hatchling.build"

[project]
name = "ntk"
description = "Template repository for python projects"
readme.content-type = "text/markdown"
readme.file = "README.md"
version = "0.2.0"
authors = [
    {name = "Cristian Ordonez", email = "cristianordonezrd@gmail.com"},
]
urls.Repository = "https://github.com/cristianordonez/nutrition-toolkit-cli.git"
requires-python = ">= 3.12"
dependencies = [
    "psycopg>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.11.0",
    "pyyaml>=6.0.3",
    "sqlmodel>=0.0.39",
]

[project.optional-dependencies]
api = [
    "fastapi>=0.139.0",
    "uvicorn>=0.51.0",
]

[project.scripts]
ntk = "ntk.presentation.cli.app:main"
ntk-api = "ntk.presentation.api.main:start"

[dependency-groups]
dev = [
    { include-group = "test" },
    { include-group = "docs" },
    { include-group = "fix" },
]
test = [
    "covdefaults>=2.3.0",
    "coverage>=7.14.1",
    "diff-cover>=10.3.0",
    "pytest>=8.4.2",
    "pytest-cov",
]
docs = [
    "autodoc-pydantic>=2.2.0",
    "sphinx>=7.4.7",
    "sphinx-argparse-cli>=1.21.4",
    "sphinx-rtd-theme>=3.1.0",
]
fix = [
    "pre-commit>=4.6.0",
    "pre-commit-uv"
]
type = [
    "ty>=0.0.57",
]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/ntk/_version.py"
build.dev-mode-dirs = [
  "src",
]
build.targets.sdist.include = [ 
    "src",
    "/tests",
    "/tox.toml"
]
build.targets.wheel.packages = [ "src/ntk" ]

[tool.ruff]
line-length = 88
indent-width = 4
unsafe-fixes = false
exclude = [
    ".git",
    ".venv",
    ".ruff_cache",
    ".tox",
    ".vscode",
    "dist"
]
lint.select = [ "ALL" ] # Select which linting rules to use
lint.ignore = [
    "D100", # Ignore missing docstring in public modules
    "D101", # Ignore missing docstring in public class
    "D104", # Missing docstring in public package
    "D203", # incorrect blank line before class, conflicts with D211
    "D213", # multi line summary second line, conflicts with D212
] # Avoid enforcing specific violations
lint.fixable = [ "ALL" ] # Allow fix for all enabled rules (when `--fix`) is provided.
lint.unfixable = [ "F401" ] # Disables automatic or removal of unused imports, will still fail ruff checks
lint.per-file-ignores."!src/**.py" = [ "D" ] # Don't care about documentation in non package files
lint.per-file-ignores."tests/**/*.py" = [ "S101" ] # allow assert command in tests
lint.flake8-errmsg.max-string-length = 30 # Max length of string literal in error message
lint.flake8-import-conventions.banned-from = [ "typing" ]
lint.isort = { known-first-party = [
    "tox", "tests"
], required-imports = [
    "from __future__ import annotations"
]}
format.docstring-code-line-length = "dynamic"
format.skip-magic-trailing-comma = false
format.line-ending = "auto"
format.quote-style = "double"
format.docstring-code-format = true
format.indent-style = "space"

[tool.ty]
environment.python-version = "3.14"
environment.root = ["./src"]
src.include = [
    "src",
    "tests",
]

[tool.codespell]
count = true
quiet-level = 3

[tool.pytest]
ini_options.testpaths = [
  "tests",
]
ini_options.filterwarnings = [
    "ignore:unclosed database in <sqlite3.Connection object at:ResourceWarning",
]


[tool.coverage]
run.parallel = true
run.plugins = [
  "covdefaults",
]
paths.source = [
  "src",
  ".tox*/*/lib/python*/site-packages",
  ".tox*/pypy*/site-packages",
  ".tox*\\*\\Lib\\site-packages",
  "*/src",
  "*\\src",
]
report.fail_under = 88
report.omit = []
html.show_contexts = true
html.skip_covered = false
