requires = [ "tox>=4.54" ]
env_list = [
    "3.15",
    "3.14",
    "3.13",
    "3.12",
    "docs",
    "fix",
    "type"
]
skip_missing_interpreters = true

[env_run_base]
description = "Run pytest for python package"
package = "wheel"
dependency_groups = [ "test" ]
set_env.COVERAGE_FILE = { replace = "env", name = "COVERAGE_FILE", default = "{work_dir}{/}.coverage.{env_name}" }
commands = [
  [
    "pytest",
    { replace = "posargs", default = [
      "--cov=ntk",
      "--cov-report",
      "term-missing",
      "--cov-report",
      "xml:{work_dir}{/}coverage.{env_name}.xml",
      "tests",
    ], extend = true },
  ],
  [
    "diff-cover",
    "--compare-branch",
    { replace = "env", name = "DIFF_AGAINST", default = "origin/main" },
    "{work_dir}{/}coverage.{env_name}.xml",
  ],
]
uv_seed = true

[env.docs]
description = "build the docs"
dependency_groups = [ "docs" ]
base_python = [ "3.14" ]
commands = [
  [
    "sphinx-build",
    "-b",
    "html",
    "docs/",
    "{env:READTHEDOCS_OUTPUT:{work_dir}{/}docs_out}/html", # uses READTHEDOCS_OUTPUT/html when building on readthedocs otherwise local .tox dir
    { replace = "posargs", default = [], extend = true },
  ],
  [
    "python",
    "-c",
    'print(r"documentation available under file://{work_dir}{/}docs_out{/}html{/}index.html")',
  ]
]

[env.fix]
description = "lint and format check the code base and complain about what we cannot do automatically"
skip_install = true
dependency_groups = [ "fix" ]
commands = [ [
    "pre-commit", 
    "run", 
    "--all-files", 
    "--show-diff-on-failure", 
    { replace = "posargs", extend = true } 
] ]

[env.type]
description = "type check the code base"
skip_install = false
dependency_groups = [ "type", "test" ]
commands = [ [
    "ty", 
    "check", 
    { replace = "posargs", extend = true } 
] ]