"""CLI command for assessment generation."""

from __future__ import annotations

import typing

from pydantic import BaseModel, Field

from ntk.controllers.base import BaseController
from ntk.controllers.session import controller_session
from ntk.models.base import ConsoleRenderableModel
from ntk.models.output import Output
from ntk.models.sql.resident import ResidentAssessment  # noqa: TC001
from ntk.repositories.assessment_repo import AssessmentRepo
from ntk.repositories.embedding_repo import EmbeddingRepo
from ntk.repositories.resident_repo import ResidentRepo
from ntk.services.assessment import AssessmentGenerationService

if typing.TYPE_CHECKING:
    from sqlmodel import Session


class AssessmentGenerateCommandOptions(BaseModel):
    """Residents and optional guidance for assessment generation."""

    resident_identifiers: list[str] = Field(
        min_length=1,
        description="Facility resident identifiers",
    )
    facility_id: str | None = Field(
        default=None,
        min_length=1,
        description="Optional external facility identifier",
    )
    context: str | None = Field(
        default=None,
        description="Optional assessment focus or additional context",
    )


class AssessmentGenerateCommandResult(ConsoleRenderableModel):
    """Assessments generated by the CLI command."""

    assessments: list[ResidentAssessment]

    def to_console(self) -> str:
        """Render generated assessments as formatted JSON."""
        return self.model_dump_json(indent=2)


class AssessmentGenerateCommandController(BaseController):
    """Invoke the assessment generation service from the CLI."""

    name = "generate"
    help = "Generate resident assessments"
    options_model = AssessmentGenerateCommandOptions

    def __init__(self, session: Session | None = None) -> None:
        """Store the optional controller-owned session."""
        self.session = session

    async def run(
        self,
        options: AssessmentGenerateCommandOptions,
    ) -> Output[AssessmentGenerateCommandResult]:
        """Generate assessments for the requested residents."""
        assessments: list[ResidentAssessment] = []
        seen: set[str] = set()
        with controller_session(self.session) as session:
            resident_repository = ResidentRepo(session)
            service = AssessmentGenerationService(
                resident_repository,
                AssessmentRepo(session),
                EmbeddingRepo(session),
            )
            for resident_identifier in options.resident_identifiers:
                if resident_identifier in seen:
                    continue
                seen.add(resident_identifier)
                assessments.append(
                    await service.generate(
                        resident_identifier,
                        facility_id=options.facility_id,
                        context=options.context,
                    ),
                )
        return Output(
            result=AssessmentGenerateCommandResult(assessments=assessments),
            controller=self.name,
            exit_code=0,
        )


__all__ = [
    "AssessmentGenerateCommandController",
    "AssessmentGenerateCommandOptions",
    "AssessmentGenerateCommandResult",
]
