"""initial

Revision ID: 20260912_0001
Revises:
Create Date: 2026-09-12 17:23:24.023083
"""

from __future__ import annotations

import typing

from alembic import op

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "20260912_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("person_diet_person_id_state_key_key"),
        "person_diet",
        type_="unique",
    )
    op.create_unique_constraint(
        "person_diet_person_id_key",
        "person_diet",
        ["person_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration when doing so is safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "person_diet_person_id_key",
        "person_diet",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("person_diet_person_id_state_key_key"),
        "person_diet",
        ["person_id", "state_key"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
