"""Persisted SQLModel tables used by the application."""

from __future__ import annotations

from .api_key import APIKey, APIKeyPermission, Permission
from .clinical import (
    AI_CAPABLE_STRUCTURED_MODELS,
    DETERMINISTIC_FIRST_MODELS,
    AppetiteLevel,
    ClinicalFactType,
    ClinicalStatus,
    DentitionStatus,
    DentureStatus,
    DialysisType,
    FeedingMethod,
    FoodPreferenceReason,
    FoodPreferenceType,
    FoodPreferenceValue,
    GISymptom,
    LipidDeliveryType,
    NutritionGoalType,
    ParenteralAccessRoute,
    ParenteralFormulaType,
    ParenteralNutritionStatus,
    PersonAllergy,
    PersonAppetiteObservation,
    PersonClinicalFact,
    PersonDiagnosis,
    PersonDialysis,
    PersonDiet,
    PersonEdema,
    PersonEnteralFeeding,
    PersonFluidPlan,
    PersonFoodPreference,
    PersonGIObservation,
    PersonLab,
    PersonMealIntake,
    PersonMedication,
    PersonMiscOrder,
    PersonNutritionGoal,
    PersonOralFeedingStatus,
    PersonParenteralNutrition,
    PersonSupplement,
    PersonWeight,
    PersonWound,
    WeightContext,
)
from .document import Document, DocumentSource, DocumentSourceType, SourceAuthority
from .extracted_fact import ExtractedFact, ExtractionMethod, build_fact_key
from .facility import Facility
from .food import (
    Food,
    FoodCategory,
    FoodNutrient,
    FoodSyncState,
    Nutrient,
    NutrientClassification,
)
from .knowledge import Knowledge, KnowledgeChunk, KnowledgeChunkEmbedding
from .person import (
    AssessmentSource,
    Person,
    PersonAssessment,
    PersonAssessmentEmbedding,
    PersonProgressNote,
    StatusType,
)
from .user import User, UserHash

__all__ = [
    "AI_CAPABLE_STRUCTURED_MODELS",
    "DETERMINISTIC_FIRST_MODELS",
    "APIKey",
    "APIKeyPermission",
    "AppetiteLevel",
    "AssessmentSource",
    "ClinicalFactType",
    "ClinicalStatus",
    "DentitionStatus",
    "DentureStatus",
    "DialysisType",
    "Document",
    "DocumentSource",
    "DocumentSourceType",
    "ExtractedFact",
    "ExtractionMethod",
    "Facility",
    "FeedingMethod",
    "Food",
    "FoodCategory",
    "FoodNutrient",
    "FoodPreferenceReason",
    "FoodPreferenceType",
    "FoodPreferenceValue",
    "FoodSyncState",
    "GISymptom",
    "Knowledge",
    "KnowledgeChunk",
    "KnowledgeChunkEmbedding",
    "LipidDeliveryType",
    "Nutrient",
    "NutrientClassification",
    "NutritionGoalType",
    "ParenteralAccessRoute",
    "ParenteralFormulaType",
    "ParenteralNutritionStatus",
    "Permission",
    "Person",
    "PersonAllergy",
    "PersonAppetiteObservation",
    "PersonAssessment",
    "PersonAssessmentEmbedding",
    "PersonClinicalFact",
    "PersonDiagnosis",
    "PersonDialysis",
    "PersonDiet",
    "PersonEdema",
    "PersonEnteralFeeding",
    "PersonFluidPlan",
    "PersonFoodPreference",
    "PersonGIObservation",
    "PersonLab",
    "PersonMealIntake",
    "PersonMedication",
    "PersonMiscOrder",
    "PersonNutritionGoal",
    "PersonOralFeedingStatus",
    "PersonParenteralNutrition",
    "PersonProgressNote",
    "PersonSupplement",
    "PersonWeight",
    "PersonWound",
    "SourceAuthority",
    "StatusType",
    "User",
    "UserHash",
    "WeightContext",
    "build_fact_key",
]
