"""initial cloud-api schema

Revision ID: 20260915_0000
Revises:
Create Date: 2026-09-15 11:49:55.638914
"""

# Autogenerated schema-creation migration intentionally keeps its generated
# shape (long lines, many statements).
# ruff: noqa: E501

from __future__ import annotations

import typing

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel
from alembic import op

if typing.TYPE_CHECKING:
    from collections.abc import Sequence

revision: str = "20260915_0000"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "food_category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("USDA", "FATSECRET", "INTERNAL", name="foodcategorysource"),
            nullable=True,
        ),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "food_sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "USDA_BRANDED",
                "USDA_FNDDS",
                "USDA_FOUNDATION",
                "USDA_SR_LEGACY",
                "FATSECRET",
                "MANUFACTURER",
                "INTERNAL",
                name="foodsourcetype",
            ),
            nullable=False,
        ),
        sa.Column("last_completed_page", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_food_sync_state_source"), "food_sync_state", ["source"], unique=True,
    )
    op.create_table(
        "knowledge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "knowledge_type",
            sa.Enum(
                "diet-manual",
                "nutrition-care-manual",
                name="knowledge_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_file_hash"), "knowledge", ["file_hash"], unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_knowledge_type"),
        "knowledge",
        ["knowledge_type"],
        unique=False,
    )
    op.create_table(
        "nutrient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("unit_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "MACRONUTRIENT", "VITAMIN", "MINERAL", name="nutrientclassification",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nutrition_care_process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "person_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=False,
        ),
        sa.Column(
            "facility_identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True,
        ),
        sa.Column("note_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "ncp_source",
            sa.Enum(
                "generated",
                "imported",
                name="nutrition_care_process_source",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "finalized", "discarded", name="nutrition_care_process_status",
            ),
            nullable=False,
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finalized_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "person_identifier", "content_hash", name="uq_ncp_person_content_hash",
        ),
    )
    op.create_index(
        op.f("ix_nutrition_care_process_content_hash"),
        "nutrition_care_process",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_care_process_created_at"),
        "nutrition_care_process",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_care_process_facility_identifier"),
        "nutrition_care_process",
        ["facility_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_care_process_ncp_source"),
        "nutrition_care_process",
        ["ncp_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_care_process_person_identifier"),
        "nutrition_care_process",
        ["person_identifier"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_care_process_source_filename"),
        "nutrition_care_process",
        ["source_filename"],
        unique=False,
    )
    op.create_index(
        op.f("ix_nutrition_care_process_status"),
        "nutrition_care_process",
        ["status"],
        unique=False,
    )
    op.create_table(
        "permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_name"), "permission", ["name"], unique=True)
    op.create_table(
        "api_key_permission",
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_key.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.PrimaryKeyConstraint("api_key_id", "permission_id"),
    )
    op.create_table(
        "food",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "food_type",
            sa.Enum("FOOD", "ORAL_SUPPLEMENT", "ENTERAL_FORMULA", name="foodtype"),
            nullable=False,
        ),
        sa.Column(
            "source_type",
            sa.Enum(
                "USDA_BRANDED",
                "USDA_FNDDS",
                "USDA_FOUNDATION",
                "USDA_SR_LEGACY",
                "FATSECRET",
                "MANUFACTURER",
                "INTERNAL",
                name="foodsourcetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "import_method",
            sa.Enum("API", "MANUAL", name="importmethod"),
            nullable=False,
        ),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("gtin_upc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ingredients", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("serving_size", sa.Float(), nullable=True),
        sa.Column("serving_unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "liquid_consistency",
            sa.Enum(
                "THIN",
                "SLIGHTLY_THICK",
                "MILDLY_THICK",
                "MODERATELY_THICK",
                "EXTREMELY_THICK",
                name="liquidconsistency",
            ),
            nullable=True,
        ),
        sa.Column(
            "package_type",
            sa.Enum("READY_TO_HANG", "CARTON", "BOTTLE", "CAN", name="packagetype"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("source_published_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["food_category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_type", "source_id", name="uq_food_source"),
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("knowledge_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("section_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_page_start", sa.Integer(), nullable=True),
        sa.Column("source_page_end", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "source_page_end IS NULL OR source_page_start IS NULL OR source_page_end >= source_page_start",
            name="ck_knowledge_chunks_source_page_range",
        ),
        sa.CheckConstraint(
            "source_page_start IS NULL OR source_page_start >= 1",
            name="ck_knowledge_chunks_source_page_start",
        ),
        sa.ForeignKeyConstraint(
            ["knowledge_id"],
            ["knowledge.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_id", "chunk_index"),
    )
    op.create_index(
        op.f("ix_knowledge_chunks_knowledge_id"),
        "knowledge_chunks",
        ["knowledge_id"],
        unique=False,
    )
    op.create_table(
        "nutrition_care_process_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding_vector",
            pgvector.sqlalchemy.VECTOR(dim=384).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("nutrition_care_process_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "Nutrition/Dietary",
                "Dietician",
                name="nutrition_clinical_note_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["nutrition_care_process_id"],
            ["nutrition_care_process.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrition_care_process_embeddings_type"),
        "nutrition_care_process_embeddings",
        ["type"],
        unique=False,
    )
    op.create_index(
        "ix_nutrition_care_process_embeddings_vector_hnsw",
        "nutrition_care_process_embeddings",
        ["embedding_vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
    )
    op.create_index(
        "uq_nutrition_care_process_embedding_ncp_id",
        "nutrition_care_process_embeddings",
        ["nutrition_care_process_id"],
        unique=True,
    )
    op.create_table(
        "food_nutrient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("food_id", sa.Integer(), nullable=False),
        sa.Column("nutrient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["food.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nutrient_id"],
            ["nutrient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_chunks_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("knowledge_chunk_id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding_vector",
            pgvector.sqlalchemy.VECTOR(dim=384).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_chunk_id"],
            ["knowledge_chunks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_knowledge_chunks_embeddings_embedding_vector_hnsw",
        "knowledge_chunks_embeddings",
        ["embedding_vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_knowledge_chunks_embeddings_knowledge_chunk_id"),
        "knowledge_chunks_embeddings",
        ["knowledge_chunk_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration when doing so is safe."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_knowledge_chunks_embeddings_knowledge_chunk_id"),
        table_name="knowledge_chunks_embeddings",
    )
    op.drop_index(
        "ix_knowledge_chunks_embeddings_embedding_vector_hnsw",
        table_name="knowledge_chunks_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
    )
    op.drop_table("knowledge_chunks_embeddings")
    op.drop_table("food_nutrient")
    op.drop_index(
        "uq_nutrition_care_process_embedding_ncp_id",
        table_name="nutrition_care_process_embeddings",
    )
    op.drop_index(
        "ix_nutrition_care_process_embeddings_vector_hnsw",
        table_name="nutrition_care_process_embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"embedding_vector": "vector_cosine_ops"},
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_embeddings_type"),
        table_name="nutrition_care_process_embeddings",
    )
    op.drop_table("nutrition_care_process_embeddings")
    op.drop_index(
        op.f("ix_knowledge_chunks_knowledge_id"), table_name="knowledge_chunks",
    )
    op.drop_table("knowledge_chunks")
    op.drop_table("food")
    op.drop_table("api_key_permission")
    op.drop_index(op.f("ix_permission_name"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(
        op.f("ix_nutrition_care_process_status"), table_name="nutrition_care_process",
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_source_filename"),
        table_name="nutrition_care_process",
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_person_identifier"),
        table_name="nutrition_care_process",
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_ncp_source"),
        table_name="nutrition_care_process",
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_facility_identifier"),
        table_name="nutrition_care_process",
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_created_at"),
        table_name="nutrition_care_process",
    )
    op.drop_index(
        op.f("ix_nutrition_care_process_content_hash"),
        table_name="nutrition_care_process",
    )
    op.drop_table("nutrition_care_process")
    op.drop_table("nutrient")
    op.drop_index(op.f("ix_knowledge_knowledge_type"), table_name="knowledge")
    op.drop_index(op.f("ix_knowledge_file_hash"), table_name="knowledge")
    op.drop_table("knowledge")
    op.drop_index(op.f("ix_food_sync_state_source"), table_name="food_sync_state")
    op.drop_table("food_sync_state")
    op.drop_table("food_category")
    op.drop_table("api_key")
    # ### end Alembic commands ###
