"""Persisted SQLModel tables used by the desktop engine."""

from __future__ import annotations

from .clinical import (
    AI_CAPABLE_STRUCTURED_MODELS,
    DETERMINISTIC_FIRST_MODELS,
    AppetiteLevel,
    ClinicalFactType,
    ClinicalStatus,
    DentitionStatus,
    DentureStatus,
    DialysisType,
    FeedingMethod,
    FoodPreferenceReason,
    FoodPreferenceType,
    FoodPreferenceValue,
    GISymptom,
    LipidDeliveryType,
    NutritionGoalType,
    ParenteralAccessRoute,
    ParenteralFormulaType,
    ParenteralNutritionStatus,
    PersonAllergy,
    PersonAppetiteObservation,
    PersonClinicalFact,
    PersonDiagnosis,
    PersonDialysis,
    PersonDiet,
    PersonEdema,
    PersonEnteralFeeding,
    PersonFluidPlan,
    PersonFoodPreference,
    PersonGIObservation,
    PersonLab,
    PersonMealIntake,
    PersonMedication,
    PersonMiscOrder,
    PersonNutritionGoal,
    PersonOralFeedingStatus,
    PersonParenteralNutrition,
    PersonSupplement,
    PersonWeight,
    PersonWound,
    WeightContext,
)
from .document import Document, DocumentSource, DocumentSourceType, SourceAuthority
from .extracted_fact import ExtractedFact, ExtractionMethod, build_fact_key
from .facility import Facility
from .person import (
    ExtractionStatus,
    Person,
    PersonClinicalNote,
)

__all__ = [
    "AI_CAPABLE_STRUCTURED_MODELS",
    "DETERMINISTIC_FIRST_MODELS",
    "AppetiteLevel",
    "ClinicalFactType",
    "ClinicalStatus",
    "DentitionStatus",
    "DentureStatus",
    "DialysisType",
    "Document",
    "DocumentSource",
    "DocumentSourceType",
    "ExtractedFact",
    "ExtractionMethod",
    "ExtractionStatus",
    "Facility",
    "FeedingMethod",
    "FoodPreferenceReason",
    "FoodPreferenceType",
    "FoodPreferenceValue",
    "GISymptom",
    "LipidDeliveryType",
    "NutritionGoalType",
    "ParenteralAccessRoute",
    "ParenteralFormulaType",
    "ParenteralNutritionStatus",
    "Person",
    "PersonAllergy",
    "PersonAppetiteObservation",
    "PersonClinicalFact",
    "PersonClinicalNote",
    "PersonDiagnosis",
    "PersonDialysis",
    "PersonDiet",
    "PersonEdema",
    "PersonEnteralFeeding",
    "PersonFluidPlan",
    "PersonFoodPreference",
    "PersonGIObservation",
    "PersonLab",
    "PersonMealIntake",
    "PersonMedication",
    "PersonMiscOrder",
    "PersonNutritionGoal",
    "PersonOralFeedingStatus",
    "PersonParenteralNutrition",
    "PersonSupplement",
    "PersonWeight",
    "PersonWound",
    "SourceAuthority",
    "WeightContext",
    "build_fact_key",
]
