name: "Release Workflow"
on:
    workflow_dispatch:
      inputs:
        version:
          description: "Release version"
          required: true
          type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Create and Push Git Tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Creating annotated tag: ${{ inputs.version }}"
          git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }} via GitHub Actions"
          git push origin "${{ inputs.version }}"
      - name: Create Release
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ inputs.version }}" --title "Release ${{ inputs.version }}" --notes "Release ${{ inputs.version }} via GitHub Actions"
      # build docker image
      # publish docker image
      # ssh into droplet and pull docker image then start the service
