name: "Release Workflow"
on:
    workflow_dispatch:
      inputs:
        version:
          description: "Release version"
          required: true
          type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Create and Push Git Tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Creating annotated tag: ${{ inputs.version }}"
          git tag -a "${{ inputs.version }}" -m "Release ${{ inputs.version }} via GitHub Actions"
          git push origin "${{ inputs.version }}"
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Python 3.14
        run: uv python install 3.14
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
      # ssh into droplet and install latest version of package
